export enum Input {
    FULLNAME,
    APPENDED_TEXT,
    TEXTBOX,
    CLEAR_TEXT,
    EDIT_FIELD,
    READONLY,
    FORM_FIRSTNAME,
    FORM_LASTNAME,
    FORM_EMAIL,
    FORM_PHONE,
    FORM_ADDRESS1,
    FORM_ADDRESS2,
    FORM_STATE,
    FORM_POSTALCODE
}